runtime: php
env: flex

runtime_config:
  document_root: .
  skip_lockdown_document_root: true

env_variables:
  MYSQL_HOST: mysql:unix_socket=/cloudsql/cst-323-gcp:us-west4:cst-323-gcp-db
  MYSQL_DB: student
  MYSQL_USER: ricardo
  MYSQL_PASS: gcpTest1DB



manual_scaling: 
  instances: 1
resources:
  cpu: 0.25
  memory_gb: 0.50
  disk_size_gb: 0.25

